### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_nadezhdababenko#1]
Hey @ NadezhdaBabenko lets keep track of you app concept here in your final project repo.

So far I understand you are interested in making a "Social network for reading enthusiasts" is that correct?

What features would your app have?

**Comment by NadezhdaBabenko** [comment]
Hello! Yes, it is my idea and I think that I will be really interesting for me .. What do you think about it? Is it good for ReDi project?
Features:
- Convenient service for searching books and reading
  - important
    - you can read
    - screen color adjustment
    - font size adjustment
    - flipping control
    - text alignment
    - screen brightness
    - chapter search
  - Interesting
    - creating notes while reading
    - brief information about the book (author, abstract)
    - the ability to translate pieces of text into their native language
    - creating a quote box
- getting personal book recommendations
- communication in a circle of like-minded people
- tracking book interests of friends
- writing articles about read / personal blog
- create your own top list

**Comment by MrTim** [comment]
Quite interesting idea! Which is good :) Even though sounds like "Cool reader" or similar apps. 
But this is quite a big application from what you described and I doubt that you would be able to do it in one month. But we can just limit the scope! 
So maybe you can write which features you want to do first and after you ofc can continue working on this project.

**Comment by BTBTravis** [comment]
The initial site is committed. Lets create more issues to track the next steps
